### ISSUE TITLE
Lab2 - route missing

### ISSUE THREAD

**Issue by marcelkmfst** [bhavinbdoshi/azure-networking-labs#1]
Hi Bhavin, in lab2 there is a route missing. The on-prem VNET is not learning the spoke via BGP as there is no BGP endpoint deployed. hence a route is needed to forward all traffic to the spoke VNET via the internal on-prem CSR interface

    az network route-table route create --name vm-rt --resource-group $rgonprem --route-table-name onprem-vm-rt --address-prefix 10.10.0.0/16 --next-hop-type VirtualAppliance --next-hop-ip-address 10.100.1.4 -o none

**Comment by bhavinbdoshi** [comment]
this is in lab 1. There is static route in onprem-vm-rt route-table which simulates all 10/8 traffic via CSR on-prem
